import Section from "../Section/Section";
import X from "../../assets/icons/add-sharp.svg?react";
import * as s from "./About.styled";
import { useScreenWidth } from "../../hooks/useScreenWidth";
import { aboutImageAdaptive } from "../../data/aboutImage";
import { useEffect, useState } from "react";
import Banner from "../Banner/Banner";

const About = () => {
  const screenWidth = useScreenWidth();
  const [imageAdaptive, setImageAdaptive] = useState(
    aboutImageAdaptive[screenWidth]
  );

  useEffect(() => {
    setImageAdaptive(aboutImageAdaptive[screenWidth]);
  }, [screenWidth]);

  return (
    <>
      <Section id="about">
        <s.Title>
          a Story that started with{" "}
          <span>
            one simple <br /> ape
          </span>
        </s.Title>
        <s.Text>
          WHO GOT <br />
          FED UP WITH BORING <br />
          AND HYPOCRITIC <br />
          COMMONPLACE THIS IS <br />
          HOW THE IDEA OF <br />
          ESCAPING AND DYNAMIC <br />
          JOURNEY ON THE YACHT
        </s.Text>
        <s.WrapSecondaryText>
          <X />
          <s.SecondaryText>
            EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY. ARTS
            ARE RANDOMLY GENERATED BY USERS
          </s.SecondaryText>
        </s.WrapSecondaryText>
        <picture>
          <source
            srcSet={`${imageAdaptive.oneWebpX} 1x, ${imageAdaptive.twoWebpX} 2x`}
          />
          <source
            srcSet={`${imageAdaptive.oneX} 1x, ${imageAdaptive.twoX} 2x`}
          />
          <img src={imageAdaptive.oneX} alt="apes" />
        </picture>
      </Section>
      <Banner />
    </>
  );
};

export default About;
