import Section from "../Section/Section";
import X from "../../assets/icons/add-sharp.svg?react";
import * as s from "./About.styled";
import { useScreenWidth } from "../../hooks/useScreenWidth";
import { aboutImageAdaptive } from "../../data/aboutImage";
import { useEffect, useState } from "react";
import Banner from "../Banner/Banner";

const About = () => {
  const screenWidth = useScreenWidth();
  const [imageAdaptive, setImageAdaptive] = useState(
    aboutImageAdaptive[screenWidth]
  );

  useEffect(() => {
    setImageAdaptive(aboutImageAdaptive[screenWidth]);
  }, [screenWidth]);

  return (
    <>
      <Section id="about">
        <s.Wrapper>
          <s.Title>
            a Story that started with <span>one simple {"\n"}ape</span>
          </s.Title>
          <s.Text>
            WHO GOT FED UP WITH BORING AND HYPOCRITIC COMMONPLACE THIS IS HOW
            THE IDEA OF ESCAPING AND DYNAMIC JOURNEY ON THE{"\n"} YACHT
          </s.Text>
          <s.WrapSecondaryText>
            <X />
            <s.SecondaryText>
              EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY. ARTS
              ARE RANDOMLY GENERATED BY USERS
            </s.SecondaryText>
          </s.WrapSecondaryText>
          <picture>
            <source
              srcSet={`${imageAdaptive.oneWebpX} 1x, ${imageAdaptive.twoWebpX} 2x`}
              type="image/webp"
            />
            <source
              srcSet={`${imageAdaptive.oneX} 1x, ${imageAdaptive.twoX} 2x`}
              type="image/jpeg"
            />
            <s.Img src={imageAdaptive.oneX} alt="apes" />
          </picture>
        </s.Wrapper>
      </Section>
      <Banner />
    </>
  );
};

export default About;
